# Generated by Django 5.0 on 2023-12-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_patient', models.IntegerField()),
                ('medicin_id', models.IntegerField()),
                ('consultation_data', models.DateField()),
                ('consultation_heure', models.TimeField()),
                ('symptomes', models.TextField()),
                ('diagnostic', models.TextField()),
                ('commentaire', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('date_de_naissance', models.DateField(blank=True)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('numero_de_telephone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patient_image')),
            ],
        ),
    ]
